In [1]:
### Identify missing items

import pandas as pd

# Meta data from item
items_meta_data = pd.read_csv('items.csv')
items_meta_data['item_nbr'].unique().shape # 4100



(4100,)

In [2]:
# load items from test data
test_data = pd.read_csv('test.csv')
items_in_test_data =  test_data['item_nbr'].unique()
del test_data

In [19]:
items_in_test_data # 3901

array([  96995,   99197,  103501, ..., 2132945, 2132957, 2134244], dtype=int64)

In [31]:
# check which items are not in the test data
#index = (items_in_test_data in items_meta_data['item_nbr'].values)
index = items_meta_data['item_nbr'].isin(items_in_test_data)
# items which are not in the test data
excluded_items_in_test = items_meta_data['item_nbr'][index == False]
excluded_items_in_test.shape # 199 No need to train on these items :)

(199,)

In [5]:

# read the filenames in the directory first
folder = 'train_data_by_item'
import os
item_files = os.listdir(folder)
len(item_files) - 1 # 4100

# load items from train data
train_filename = 'C:/Local/hassans/Data/FF/train/train.csv'
train_data = pd.read_csv(train_filename, usecols = ['date', 'item_nbr'], parse_dates = ['date'], dayfirst = True, index_col = 'date')

train_data.shape

(125497040, 1)

In [10]:
start_date = '2017-01-01'
end_date = '2017-08-15'
train_data['item_nbr'].loc[start_date:end_date].unique().shape

(4018,)

In [11]:
start_date = '2017-01-01'
end_date = '2017-08-15'
items_in_train_data = train_data['item_nbr'].loc[start_date:end_date].unique()
#items_in_train_data = train_data['item_nbr'].unique() # 4036
del train_data

In [12]:
items_in_train_data.shape # 4018

(4018,)

In [13]:
# check which items are not in the train data

index = items_meta_data['item_nbr'].isin(items_in_train_data)
# items which are not in the train data
excluded_items_in_train = items_meta_data['item_nbr'][index == False]
excluded_items_in_train.shape # 64 if all data considered, 82 if only given date range

(82,)

In [15]:
# check which items need to be included for training purpose

import numpy as np

index = np.in1d(items_in_test_data, items_in_train_data)

# items which should be included in train data
included_items_in_train = items_in_test_data[index == False]
included_items_in_train.shape # 60 if all date range considered, 60 if falls in certain date range

# items_in_test_data in items_in_train_data
#for a, b in 
#len(zip(items_in_test_data, items_in_train_data))
#    print(a,b)

(60,)

In [16]:
included_items_in_train # similar
# if all dates are considered
# array([ 313094, 1464607, 1467088, 1467093, 2015646, 2109969, 2112280,
#       2112303, 2112461, 2112462, 2112607, 2117783, 2118397, 2120180,
#       2120216, 2120506, 2120681, 2120768, 2121319, 2124705, 2125814,
#       2126696, 2127024, 2127069, 2127175, 2127206, 2127544, 2127651,
#       2127733, 2127825, 2127921, 2127992, 2128628, 2128799, 2129334,
#       2129350, 2129387, 2129515, 2129616, 2129678, 2129786, 2129790,
#       2129892, 2129994, 2130131, 2130219, 2130265, 2130352, 2130474,
#       2130521, 2130526, 2130553, 2131010, 2131572, 2131699, 2132163,
#       2132318, 2132945, 2132957, 2134244], dtype=int64)

array([ 313094, 1464607, 1467088, 1467093, 2015646, 2109969, 2112280,
       2112303, 2112461, 2112462, 2112607, 2117783, 2118397, 2120180,
       2120216, 2120506, 2120681, 2120768, 2121319, 2124705, 2125814,
       2126696, 2127024, 2127069, 2127175, 2127206, 2127544, 2127651,
       2127733, 2127825, 2127921, 2127992, 2128628, 2128799, 2129334,
       2129350, 2129387, 2129515, 2129616, 2129678, 2129786, 2129790,
       2129892, 2129994, 2130131, 2130219, 2130265, 2130352, 2130474,
       2130521, 2130526, 2130553, 2131010, 2131572, 2131699, 2132163,
       2132318, 2132945, 2132957, 2134244], dtype=int64)

In [55]:
items_meta_data.loc[items_meta_data['item_nbr'].isin(included_items_in_train)]

item_nbr            family  class  perishable
301     313094         GROCERY I   1042           0
2681   1464607         BEVERAGES   1114           0
2704   1467088         GROCERY I   1087           0
2705   1467093         GROCERY I   1093           0
3712   2015646         GROCERY I   1073           0
4002   2109969         GROCERY I   1060           0
4006   2112280  LIQUOR,WINE,BEER   1330           0
4007   2112303  LIQUOR,WINE,BEER   1334           0
4009   2112461         GROCERY I   1030           0
4010   2112462         GROCERY I   1030           0
4011   2112607         BEVERAGES   1118           0
4022   2117783        GROCERY II   1236           0
4023   2118397  LIQUOR,WINE,BEER   1326           0
4025   2120180         GROCERY I   1006           0
4026   2120216         GROCERY I   1006           0
4027   2120506         GROCERY I   1040           0
4028   2120681         GROCERY I   1028           0
4030   2120768         GROCERY I   1040           0
4031   2121319         BEVERAGES   1124           0
4055   2124705         GROCERY I   1040           0
4056   2125814         GROCERY I   1042           0
4057   2126696  LIQUOR,WINE,BEER   1318           0
4060   2127024         BEVERAGES   1118           0
4061   2127069         BEVERAGES   1142           0
4063   2127175         GROCERY I   1026           0
4064   2127206         GROCERY I   1040           0
4065   2127544         GROCERY I   1040           0
4066   2127651         GROCERY I   1068           0
4067   2127733         GROCERY I   1068           0
4068   2127825  LIQUOR,WINE,BEER   1302           0
4069   2127921         GROCERY I   1028           0
4070   2127992         GROCERY I   1028           0
4071   2128628         BEVERAGES   1122           0
4072   2128799         BEVERAGES   1148           0
4073   2129334         GROCERY I   1086           0
4074   2129350         GROCERY I   1086           0
4075   2129387         GROCERY I   1068           0
4076   2129515         GROCERY I   1042           0
4077   2129616         BEVERAGES   1124           0
4078   2129678         GROCERY I   1030           0
4079   2129786         GROCERY I   1016           0
4080   2129790         GROCERY I   1094           0
4081   2129892         GROCERY I   1092           0
4082   2129994         GROCERY I   1092           0
4083   2130131         GROCERY I   1092           0
4084   2130219         GROCERY I   1094           0
4085   2130265         GROCERY I   1094           0
4086   2130352         GROCERY I   1094           0
4087   2130474         GROCERY I   1064           0
4088   2130521         GROCERY I   1040           0
4089   2130526         GROCERY I   1030           0
4090   2130553  LIQUOR,WINE,BEER   1318           0
4091   2131010  LIQUOR,WINE,BEER   1328           0
4092   2131572         GROCERY I   1002           0
4093   2131699         GROCERY I   1002           0
4094   2132163         GROCERY I   1040           0
4095   2132318         GROCERY I   1002           0
4096   2132945         GROCERY I   1026           0
4097   2132957         GROCERY I   1068           0
4099   2134244  LIQUOR,WINE,BEER   1364           0